### ISSUE TITLE
引入失败

### ISSUE THREAD

**Issue by GreenVegetables** [zhusonger/androidz_media#1]
hello @zhusonger 

我想使用这个仓库，但是无法引入，能帮忙看看是什么情况吗

引入代码
implementation 'com.github.zhusonger:zmeida:1.1.0'

错误：
Unable to resolve dependency for ':audio_mixer@debug/compileClasspath': Could not resolve com.github.zhusonger:zmeida:1.1.0.

**Comment by GreenVegetables** [comment]
应该是我环境问题，现在引入成功了

**Comment by zhusonger** [comment]
好的
